### ISSUE TITLE
Add information around support for devfile in IDE extensions

### ISSUE THREAD

**Issue by mohitsuman** [devfile/devfile-web#46]
Currently, the devfile new page has information about `Tools that provide devfile support` as odo and EclipseChe.

https://devfile.io/docs/2.1.0/application-developer

We would like to add more supported tools that work with devfile-based workflow.

- [VSCode OpenShift Toolkit](https://github.com/redhat-developer/vscode-openshift-tools)
- [IntelliJ OpenShift Toolkit](https://github.com/redhat-developer/intellij-openshift-connector)

**Comment by schultzp2020** [comment]
@mohitsuman Can you open an issue [here](https://github.com/devfile/api/issues) and tag it with `area/documentation`?

**Comment by mohitsuman** [comment]
@schultzp2020 Isn't these requested changes part of the webpage ?

**Comment by michael-valdron** [comment]
Reopened as devfile/api#978
